Deployment attempt on 2024-11-28 15:13:39

diff --git a/transfer_artifact b/transfer_artifact
--- a/transfer_artifact
+++ b/transfer_artifact
@@ -39,7 +39,6 @@ USER=$(yq '.general.user' "$DIR_PATH/info.yml")
 SERVER_IP=$(yq '.general.server_ip' "$DIR_PATH/info.yml")
 PORT=$(yq '.general.port' "$DIR_PATH/info.yml")
 
-
 # Read paths
 BINARY_PATH=$(yq '.paths.binary_path' "$DIR_PATH/info.yml")
 CONFIG_PATH=$(yq '.paths.config_path' "$DIR_PATH/info.yml")
@@ -62,20 +61,25 @@ chmod 600 "$DIR_PATH/key"
 
 # Execute backup script on remote machine
 echo "Executing backup on remote machine..."
-ssh -q -T -o StrictHostKeyChecking=no -i "$DIR_PATH/key" -p "$PORT" "$USER@$SERVER_IP"  < backup_virtual_meter_server
+ssh -q -T -o StrictHostKeyChecking=no -i "$DIR_PATH/key" -p "$PORT" "$USER@$SERVER_IP" < deployment_routines/backup_virtual_meter_server
 if [ $? -ne 0 ]; then
     echo "Remote backup failed"
     exit 1
 fi
 
 # If backup successful, proceed with regular file transfer
-sftp -o StrictHostKeyChecking=no -i "$DIR_PATH/key" -P "$PORT" "$USER@$SERVER_IP" <<EOF
+
+if ! sftp -o StrictHostKeyChecking=no -i "$DIR_PATH/key" -P "$PORT" "$USER@$SERVER_IP" <<EOF
 rm "$DEST_PATH/virtual_meter_server"
 rm -r "$DEST_PATH/config"
 put "$BINARY_PATH" "$DEST_PATH/virtual_meter_server"
 mkdir "$DEST_PATH/config"
 put -r "$CONFIG_PATH" "$DEST_PATH/"
 EOF
+then
+    echo "SFTP file transfer failed"
+    exit 1
+fi
 
 # Remove the key file
 rm "$DIR_PATH/key"
