Deployment attempt on 2024-12-05 12:14:18

diff --git a/deploy_routines/restart_virtual_meter_server b/deploy_routines/restart_virtual_meter_server
--- a/deploy_routines/restart_virtual_meter_server
+++ b/deploy_routines/restart_virtual_meter_server
@@ -97,11 +97,11 @@ sleep 2  # Adjust the duration as needed
 
 
 # Check if the service is listening on the specified port
-echo "Checking if service is listening on port $PORT as user $USERNAME..."
-if sudo -u $USERNAME lsof -i:$PORT -s TCP:LISTEN; then
-    echo "Service is listening on port $PORT"
-    exit 0
-else
-    echo "Error: Service failed to bind to port $PORT"
-    exit 1
-fi
+# echo "Checking if service is listening on port $PORT as user $USERNAME..."
+# if sudo -u $USERNAME lsof -i:$PORT -s TCP:LISTEN; then
+#     echo "Service is listening on port $PORT"
+#     exit 0
+# else
+#     echo "Error: Service failed to bind to port $PORT"
+#     exit 1
+# fi
